# Generated by Django 2.2.16 on 2023-05-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20230430_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='group',
        ),
        migrations.AddField(
            model_name='preferences',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='posts.Group'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='preferences',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='user_author'),
        ),
    ]
