# Generated by Django 2.2.16 on 2023-05-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20230502_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='k_words',
            field=models.TextField(default=1, help_text='Введите ключевые слова через запятую', verbose_name='Ключевые слова'),
            preserve_default=False,
        ),
    ]
